package org.hittepit.smapapi.mapper

import org.scalatest.WordSpec
import org.scalatest.MustMatchers
import org.slf4j.LoggerFactory
import org.scalatest.BeforeAndAfterAll
import org.scalatest.BeforeAndAfter
import org.hittepit.smapapi.transaction.TransactionManager
import org.scalatest.mock.MockitoSugar
import org.hittepit.smapapi.core.Column
import org.hittepit.smapapi.core.NotNullableString

class TestColumnDefObject extends WordSpec with MustMatchers with  MockitoSugar{
  val logger = LoggerFactory.getLogger(classOf[TestColumnDefObject])
  val mapper = new BookMapper(mock[TransactionManager])

  "The Column:apply method" when{
    "invoked with a name and a PropertyType" must {
      "return a initialzed ColumnDef" in {
        val c = Column("test",NotNullableString)
        c.name must be (Some("test"))
        c.PropertyType must be(NotNullableString)
      }
    }
  }
  
  "The <~ method of a ColumnDef" when {
    "invoked with a getter method" must {
      "return a fully initialized ColumnDefinition instance" in {
        val c = Column("test",NotNullableString)
        val getter = (b:Book) => b.title
        val cdef = mapper.columnToColumnDef(c) <~ getter
        cdef.name must be("test")
        cdef.PropertyType must be(NotNullableString)
        cdef.getter must be(getter)
      }
    }
  }
  
  "The PrimaryKey:apply" when {
    "invoked with a columnDef" must {
      "retuun an initialized PrimaryKeyColumnDefinition" in {
        val c = Column("test",NotNullableString)
        val getter = (b:Book) => b.title
        val cdef = mapper.columnToColumnDef(c) <~ getter

        val primaryKey = mapper.PrimaryKey(cdef)
        primaryKey.name must be("test")
        primaryKey.PropertyType must be(NotNullableString)
        primaryKey.getter must be(getter)
      }
    }
  }
  
  "The ~> method of a PrimaryKey" when {
    "invoked with a setter method" must {
      "return a fully initialized AutoGeneratedColumn" in {
        val c = Column("test",NotNullableString)
        val getter = (b:Book) => b.title
        val cdef = mapper.columnToColumnDef(c) <~ getter
        val primaryKey = mapper.PrimaryKey(cdef)
        val setter = (b:Book,t:String) => new Book(b.id,b.isbn,t,b.author,b.price)
        
        val auto = primaryKey ~> setter
        
        auto.name must be("test")
        auto.PropertyType must be(NotNullableString)
        auto.getter must be(getter)
        auto.setter must be(setter)
      }
    }
  }
}