package org.hittepit.smapapi.mapper

import org.hittepit.smapapi.core.result.Row
import org.hittepit.smapapi.core.PropertyType

trait ColumnName {
  val name:String
}

trait ColumnType[P]{
	val PropertyType:PropertyType[P]
}


class ColumnDef[E,P](val name:String, val PropertyType:PropertyType[P]) extends ColumnType[P] with ColumnName{
  def <~(getProperty:E=>P):ColumnDefinition[E,P] = new ColumnDefinition[E,P](this.name,this.PropertyType,getProperty)
}

class ColumnDefinition[E, P](n:String, st:PropertyType[P], val g: E=>P) extends ColumnType[P] with ColumnName{
  val name=n
  val PropertyType = st
  val getter = g
  def value(t: E): P = getter(t)

  val value = (row:Row) => row.getColumnValue(name, PropertyType)
  
//  def value(index:Int)(implicit row:Row) = row.getColumnValue(index, PropertyType)
  
//  def setValue(index:Int, entity:E)(implicit ps:PreparedStatement) = {
//	  val v = value(entity)
//	  PropertyType.setColumnValue(index, v,ps)
//	}
}


class PrimaryKeyColumnDefinition[E,P](n:String, st:PropertyType[P], g: E=>P) extends ColumnDefinition[E,P](n,st,g){
  
  def ~>(setProperty:(E,P)=>E):AutoGeneratedColumn[E,P] = new AutoGeneratedColumn[E,P](this.name,this.PropertyType, this.getter,setProperty)
}


class AutoGeneratedColumn[E,P](n:String, st:PropertyType[P], g: E=>P, s:(E,P) => E) extends PrimaryKeyColumnDefinition[E,P](n,st,g){
  val setter:(E,P) => E =s
}