package org.hittepit.smapapi.mapper

import java.sql.PreparedStatement
import java.sql.ResultSet

trait ColumnDefinition[E, P]{
	val name:String
	val sqlType:SqlType[P]
	val getter: E => P
	
  def value(t: E): P = getter(t)

  def value(implicit rs: ResultSet) = sqlType.columnValue(name)
  
  def value(index:Int)(implicit rs: ResultSet) = sqlType.columnValue(index)
  
  def setValue(index:Int, entity:E)(implicit ps:PreparedStatement) = {
	  val v = value(entity)
	  sqlType.setParameter(index, v)
	}
}

trait PrimaryKeyColumnDefinition[E,P] extends ColumnDefinition[E,P]

trait AutoGeneratedColumn[E,P] extends PrimaryKeyColumnDefinition[E,P]{
  val setter:(E,P) => E 
}