package org.hittepit.smapapi.mapper

import java.sql.PreparedStatement
import java.sql.ResultSet

trait ColumnName {
  val name:String
}

trait ColumnType[P]{
	val sqlType:SqlType[P]
}

trait ColumnDefinition[E, P] extends ColumnType[P] with ColumnName{
  val getter: E => P
	
  def value(t: E): P = getter(t)

  def value(implicit rs: ResultSet) = sqlType.getColumnValue(rs,Left(name))
  
  def value(index:Int)(implicit rs: ResultSet) = sqlType.getColumnValue(rs,Right(index))
  
  def setValue(index:Int, entity:E)(implicit ps:PreparedStatement) = {
	  val v = value(entity)
	  sqlType.setColumnValue(index, v,ps)
	}
}

trait PrimaryKeyColumnDefinition[E,P] extends ColumnDefinition[E,P]

trait AutoGeneratedColumn[E,P] extends PrimaryKeyColumnDefinition[E,P]{
  val setter:(E,P) => E 
}