package org.hittepit.smapapi.mapper

import java.sql.ResultSet
import java.sql.PreparedStatement
import java.sql.Types

trait SqlType[T]{
  def columnValue(columnName:String)(implicit rs: ResultSet):T
  def columnValue(index:Int)(implicit rs: ResultSet):T
  def setParameter(index:Int,value:T)(implicit ps:PreparedStatement):Unit
}

object NotNullableVarchar extends SqlType[String]{
  def columnValue(columnName:String)(implicit rs: ResultSet) = {
    val v = rs.getString(columnName)
    if(rs.wasNull) throw new NullValueException else v
  }
  
  def columnValue(index:Int)(implicit rs: ResultSet) = {
    val v = rs.getString(index)
    if(rs.wasNull) throw new NullValueException else v
  }
  
  def setParameter(index:Int,value:String)(implicit ps:PreparedStatement) = ps.setString(index, value)
}

object NullableVarchar extends SqlType[Option[String]]{
  def columnValue(columnName:String)(implicit rs: ResultSet) = {
    val v = rs.getString(columnName)
    if(rs.wasNull) None else Some(v) 
  }
  
  def columnValue(index:Int)(implicit rs: ResultSet) = {
    val v = rs.getString(index)
    if(rs.wasNull) None else Some(v) 
  }
  
  def setParameter(index:Int,value:Option[String])(implicit ps:PreparedStatement) = value match {
    case Some(s) => ps.setString(index, s)
    case None => ps.setNull(index,Types.VARCHAR)
  }
}


object NotNullableInteger extends SqlType[Int]{
  def columnValue(columnName:String)(implicit rs: ResultSet) = {
    val v = rs.getInt(columnName)
    if(rs.wasNull) throw new NullValueException else v
  }
  
  def columnValue(index:Int)(implicit rs: ResultSet) = {
    val v = rs.getInt(index)
    if(rs.wasNull) throw new NullValueException else v 
  }
  
  def setParameter(index:Int,value:Int)(implicit ps:PreparedStatement) = ps.setInt(index, value)
}

object NullableInteger extends SqlType[Option[Int]]{
  def columnValue(columnName:String)(implicit rs: ResultSet) = {
    val v = rs.getInt(columnName)
    if(rs.wasNull) None else Some(v) 
  }
  
  def columnValue(index:Int)(implicit rs: ResultSet) = {
    val v = rs.getInt(index)
    if(rs.wasNull) None else Some(v) 
  }
  
  def setParameter(index:Int,value:Option[Int])(implicit ps:PreparedStatement) = value match {
    case Some(s) => ps.setInt(index, s)
    case None => ps.setNull(index,Types.INTEGER)
  }
}


trait ColumnDefinition[E, P]{
	val name:String
	val sqlType:SqlType[P]
	val getter: E => P
	
  def value(t: E): P = getter(t)

  def value(implicit rs: ResultSet) = sqlType.columnValue(name)
  
  def value(index:Int)(implicit rs: ResultSet) = sqlType.columnValue(index)
  
  def setValue(index:Int, entity:E)(implicit ps:PreparedStatement) = {
	  val v = value(entity)
	  sqlType.setParameter(index, v)
	}
}

trait PrimaryKeyColumnDefinition[E,P] extends ColumnDefinition[E,P]

trait AutoGeneratedColumn[E,P] extends PrimaryKeyColumnDefinition[E,P]{
  val setter:(E,P) => E 
}