package org.hittepit.smapapi.core

import org.scalatest.BeforeAndAfter
import org.scalatest.MustMatchers
import org.scalatest.WordSpec
import org.apache.commons.dbcp.BasicDataSource
import java.sql.Connection
import org.hittepit.smapapi.mapper.NotNullableVarchar
import org.hittepit.smapapi.mapper.NullableInteger

class TestInsertInSession extends WordSpec with BeforeAndAfter with MustMatchers {
  class DataSource extends BasicDataSource {
    this.setDriverClassName("org.h2.Driver")
    this.setUsername("h2")
    this.defaultAutoCommit = false
    this.defaultTransactionIsolation = Connection.TRANSACTION_READ_COMMITTED
    this.setUrl("jdbc:h2:mem:test;MVCC=TRUE")
  }

  val ds = new DataSource

  before {
    val connection = ds.getConnection()
    var st = connection.createStatement
    st.addBatch("create table TEST (id integer auto_increment,name varchar(10),valeur integer auto_increment, PRIMARY KEY(id));")
    st.addBatch("insert into TEST (id,name) values (1,'Test1');")
    st.addBatch("insert into TEST (id,name) values (2,'Test2');")
    st.addBatch("insert into TEST (id,name) values (3,'Test3');")
    st.executeBatch()
    connection.commit()
    connection.close
  }

  after {
    val connection = ds.getConnection()
    var st = connection.createStatement
    st.addBatch("delete from TEST");
    st.addBatch("drop table TEST;")
    st.executeBatch()
    connection.commit()
    connection.close
  }

  "The insert method" when {
    "called for auto-generated values" must {
      "at least return th id" in {
        val connection = ds.getConnection()
        val session = new Session(connection)
        
        val valueGenerated = session.insert("insert into TEST (name) values (?)",List(Param("toto",NotNullableVarchar)),List(("id",NullableInteger)))
        
        connection.commit
        connection.close
  
        valueGenerated.size must be(1)
        valueGenerated.keys must contain("id")
      }
      "return all the autogenerated column asked" in {
        val connection = ds.getConnection()
        val session = new Session(connection)
        
        val valueGenerated = session.insert("insert into TEST (name) values (?)",List(Param("toto",NotNullableVarchar)),List(("id",NullableInteger),("valeur",NullableInteger)))
        
        connection.commit
        connection.close
  
        valueGenerated.size must be(2)
        valueGenerated.keys must contain("id")
        valueGenerated.keys must contain("valeur")
      }
    }
  }

}